Repository Fer-Bar/Albercan-Backend, pull requests merged in 2024-04, with the labels that each got.

#6 Upgraded Bootstrap Version 5.2.3 to 5.3.3
  albercan_backend/templates/base.html
Labels: enhancement

#9 Update readme file and updated gitignore
  .gitignore
  README.md
Labels: documentation

#10 Implement picture_url property for image URL retrieval & fixed transitions in main_carousel
  pet/models.py
  pet/static/pet/css/main_carousel.css
  pet/templates/pet/main_carousel.html
  pet/templates/pet/secondary_carousel.html
  pet/templates/pet/steps_to_adopt.html
  pet/views.py
Labels: bug

#11 hice responsivo el carrusel
  pet/static/pet/css/main_carousel.css
Labels: bug

#12 Fix: Carousel Image Sizing
  pet/static/pet/css/main_carousel.css
  pet/templates/pet/main_carousel.html
Labels: bug

#14 Add tests for main page view
  pet/tests.py
Labels: enhancement
